#!/usr/bin/env python3
"""tokens.json -> dist/tokens.css. Generated files are never hand-edited."""
import json,re,os,pathlib
root=pathlib.Path(__file__).resolve().parent.parent
t=json.load(open(root/"tokens.json"))
def get(p):
    n=t
    for k in p.split("."): n=n[k]
    return n
def var(path): return "--"+path.replace(".","-")
def ref(v):
    return re.sub(r"\{([^}]+)\}",lambda m:f"var({var(m.group(1))})",v) if isinstance(v,str) else str(v)
def walk(n,path=()):
    if "$value" in n: yield ".".join(path),n; return
    for k,v in n.items():
        if not k.startswith("$"): yield from walk(v,path+(k,))
light,dark,prim=[],[],[]
for sec in ["color","space","radius","border-width","z","motion","breakpoint","density","size"]:
    for p,n in walk(t[sec],(sec,)): prim.append(f"  {var(p)}: {ref(n['$value'])};")
for p,n in walk(t["font"]["family"],("font","family")): prim.append(f"  {var(p)}: {n['$value']};")
for p,n in walk(t["font"]["weight"],("font","weight")): prim.append(f"  {var(p)}: {n['$value']};")
for p,n in walk(t["font"]["tracking"],("font","tracking")): prim.append(f"  {var(p)}: {n['$value']};")
for p,n in walk(t["font"]["style"],("font","style")): prim.append(f"  {var(p)}: {ref(n['$value'])};")
for p,n in walk(t["semantic"]["color"],("color",)):
    light.append(f"  {var(p)}: {ref(n['$value'])};"); dark.append(f"  {var(p)}: {ref(n.get('$extensions',{}).get('mode',{}).get('dark',n['$value']))};")
for p,n in walk(t["elevation"],("elevation",)):
    light.append(f"  {var(p)}: {n['$value']};"); dark.append(f"  {var(p)}: {n['$extensions']['mode']['dark']};")
out="/* GENERATED by scripts/build-tokens.py — do not edit */\n:root {\n"+"\n".join(prim)+"\n}\n"
out+=":root, :root[data-theme=\"light\"] {\n  color-scheme: light;\n"+"\n".join(light)+"\n}\n"
out+=":root[data-theme=\"dark\"] {\n  color-scheme: dark;\n"+"\n".join(dark)+"\n}\n"
out+="@media (prefers-color-scheme: dark) {\n  :root:not([data-theme=\"light\"]) {\n    color-scheme: dark;\n"+"\n".join("  "+l for l in dark)+"\n  }\n}\n"
os.makedirs(root/"dist",exist_ok=True); open(root/"dist/tokens.css","w").write(out)
dens=[]
for lv in [k for k in t["density"] if not k.startswith("$")]:
    sel=':root, [data-density="default"]' if lv=="default" else f'[data-density="{lv}"]'
    dens.append(sel+" {\n"+"\n".join(f"  --d-{k}: var(--density-{lv}-{k});" for k in t["density"][lv])+"\n}")
open(root/"dist/tokens.css","a").write("\n".join(dens)+"\n")
print("built",len(prim)+len(light),"vars")
