/**
 * Abilities that Mold Breaker (and Teravolt / Turboblaze) ignore.
 *
 * Generated by scripts/build-supplement.mjs from Bulbapedia categories.
 * Re-run that script to refresh; do not edit this file by hand.
 *
 * THERE IS NO EXCEPTION LIST, and its absence is deliberate rather than
 * unfinished. The five abilities usually named as ignorable-by-pattern but
 * immune in practice -- Comatose, Shields Down, Full Metal Body, Shadow Shield
 * and Prism Armor -- are all Generation 7+ and are not in this bundle at all,
 * so a rule about them could never fire in a Gen 1-4 app. Encoding one would be
 * a branch nothing can reach and a reader would have to verify to dismiss. If
 * this app ever grows past Gen 6, that list is the first thing to add back.
 *
 * ERA: Mold Breaker itself is a Generation 4 ability, so nothing consults this
 * before Gen 4 -- but ignorability is a property of the ABILITY, so it is not
 * era-gated here. The caller gates.
 */

/** Ability name slugs, sorted, in Gen 1-4 scope. */
export const IGNORABLE_ABILITIES: readonly string[] = [
  'battle-armor',
  'clear-body',
  'damp',
  'dry-skin',
  'filter',
  'flash-fire',
  'flower-gift',
  'heatproof',
  'hyper-cutter',
  'immunity',
  'inner-focus',
  'insomnia',
  'keen-eye',
  'leaf-guard',
  'levitate',
  'lightning-rod',
  'limber',
  'magma-armor',
  'marvel-scale',
  'motor-drive',
  'oblivious',
  'own-tempo',
  'sand-veil',
  'shell-armor',
  'shield-dust',
  'simple',
  'snow-cloak',
  'solid-rock',
  'soundproof',
  'sticky-hold',
  'storm-drain',
  'sturdy',
  'suction-cups',
  'tangled-feet',
  'thick-fat',
  'unaware',
  'vital-spirit',
  'volt-absorb',
  'water-absorb',
  'water-veil',
  'white-smoke',
  'wonder-guard',
]

const IGNORABLE = new Set(IGNORABLE_ABILITIES)

/** Whether Mold Breaker ignores this ability. */
export function abilityIsIgnorable(abilityName: string): boolean {
  return IGNORABLE.has(abilityName)
}

export const IGNORABLE_ABILITY_COUNT = IGNORABLE_ABILITIES.length
