/**
 * The Black/White animated sprites, as animated WebP.
 *
 * WHAT THE API ACTUALLY HAS, audited rather than assumed. PokeAPI's sprite repo
 * carries exactly one animated set: `versions/generation-v/black-white/animated`,
 * and it is GIF. Eight directories give the axes --
 *
 *   animated/{id}.gif                    front  regular
 *   animated/shiny/{id}.gif              front  shiny
 *   animated/back/{id}.gif               back   regular
 *   animated/back/shiny/{id}.gif         back   shiny
 *   animated/female/{id}.gif             front  regular  female
 *   animated/shiny/female/{id}.gif       front  shiny    female
 *   animated/back/female/{id}.gif        back   regular  female
 *   animated/back/shiny/female/{id}.gif  back   shiny    female
 *
 * -- for a total of 2,340 files covering all 493 in-scope species. Emerald and
 * Crystal animated in-game and have NO animated sprites upstream; the only other
 * animated source is `sprites.other.showdown`, which is one modern style rather
 * than per-game and is not a sanctioned source.
 *
 * THE GIFS ARE ALREADY TRANSPARENT -- audited across 18 species, every corner
 * pixel is alpha 0. The white that GIF conversion is notorious for is the RGB
 * *under* those pixels, which only surfaces if something interpolates them. The
 * WebP conversion is lossless and (by cwebp's default, i.e. not -exact) rewrites
 * the colour of fully-transparent pixels while compressing, so that white is
 * gone from the asset; the app additionally draws these nearest-neighbour, so
 * nothing interpolates them either.
 *
 * SIZE, MEASURED: 90.0 MiB of GIF became 86.3 MiB of WebP. Converting bought
 * essentially nothing in bytes for sprites this small -- the win is a single
 * animated format across the tab and 8-bit alpha instead of GIF's 1 bit.
 *
 * HOSTED ALONGSIDE THE EXISTING ARTWORK, in pokeapp-sprites, under four release
 * tags of its own -- GitHub caps a release at 1000 assets and the four
 * generations are 688 / 488 / 612 / 552. The filenames carry `-bw-` so they can
 * never collide with the {id}-front-{n|s} artwork already in that repo.
 *
 *   {RELEASE_BASE}/bw-gen{N}/{iii}-bw-{front|back}-{n|s}[-f].webp
 *
 * THESE ARE GEN 5 ART OF GEN 1-4 SPECIES, which is worth saying out loud in an
 * app whose scope is Gen 1-4: the SPECIES are all in scope, the GAME they were
 * drawn for is not, and the section that shows them names Black/White so a reader
 * is never told these are what Red/Blue looked like.
 */

import { getGenerationForSpecies } from './generations'

const SPRITE_REPO = 'hrezende423/pokeapp-sprites'
const RELEASE_BASE = `https://github.com/${SPRITE_REPO}/releases/download`

export interface BwSlot {
  side: 'front' | 'back'
  shiny: boolean
  female: boolean
}

/** Bit position of a slot in the availability mask below. */
function slotBit(slot: BwSlot): number {
  return (slot.female ? 4 : 0) + (slot.side === 'back' ? 2 : 0) + (slot.shiny ? 1 : 0)
}

/**
 * WHICH OF THE EIGHT SLOTS EXIST, one byte per species, dex 1..493 in order, hex.
 *
 * The same technique the per-game sprite slots already use, and for the same
 * reason: the set is sparse in a way no rule predicts, so the file census IS the
 * rule. Two facts it encodes that would otherwise be guesses --
 *
 *   0x0f  397 species: front/back x regular/shiny, no female file.
 *   0xff   92 species: all eight.
 *   0x0d    3 species (96 Drowzee, 98 Krabby, 99 Kingler) have NO front-shiny
 *           animated GIF upstream, and 0xfd is 97 Hypno, same gap with female
 *           files. A genuine hole in the source, not a naming variation.
 *
 * Eevee (133) is flagged has_gender_differences in the bundle but has no female
 * animated GIF, so it is 0x0f. The mask is authoritative over the flag here: the
 * flag says the species differs, the mask says which FILES exist.
 *
 * Generated by scripts/audit-bw-sprites.mjs, which reads the eight directory
 * listings from the GitHub API.
 */
const BW_MASK_HEX =
  '0f0fff0f0f0f0f0f0f0f0fff0f0f0f0f0f0fffff0f0f0f0fffff0f0f0f0f0f0f0f0f0f0f0f0f0f0fffff0fffff0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0fff' +
  'ff0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0fffff0f0f0f0f0f0f0f0f0f0f0dfd0d0d0f0f0f0f0f0f0f0f0f0f0fffff0f0f0f0f0fffff0f0f0fff0f0f0f0f0f' +
  'ffff0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0fff0f0f0f0f0f0f0f0f0f0fffff0f0f0f0f0f0f0f0f0f0f0fff0f0f0f0f0f0fffff0f0f0fff0f0f' +
  '0fffff0f0fff0f0f0fffff0f0f0fffff0f0f0fff0fffff0fff0f0f0fff0f0fff0f0f0f0fff0f0fff0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0fffff' +
  'ff0f0f0f0f0f0f0f0f0fff0fff0f0fff0fffff0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0fffff0f0f0f0f0f0fffffff0f0f0f' +
  '0fffff0f0f0f0f0f0f0f0fff0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0fff0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0fff0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f' +
  '0f0f0f0f0f0f0f0f0f0f0fffffffffffffffffffff0fff0f0f0f0f0f0f0fff0fffffff0f0f0f0fff0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0fffffff0f0f0f' +
  'ffff0f0fffff0fffff0fffffff0f0fffff0f0f0f0f0f0f0fff0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f'

export const BW_FIRST_ID = 1
export const BW_LAST_ID = 493

function maskFor(id: number): number {
  if (id < BW_FIRST_ID || id > BW_LAST_ID) return 0
  const at = (id - BW_FIRST_ID) * 2
  return parseInt(BW_MASK_HEX.slice(at, at + 2), 16)
}

/** Whether this species has that animated slot upstream. */
export function hasBwAnimated(id: number, slot: BwSlot): boolean {
  return (maskFor(id) & (1 << slotBit(slot))) !== 0
}

/**
 * Release URL for one animated slot, or null when the file does not exist.
 *
 * Null rather than a fabricated URL, so a missing slot is an absent card instead
 * of a broken image -- the same contract getSpriteUrl keeps.
 */
export function bwAnimatedUrl(id: number, slot: BwSlot): string | null {
  const generation = getGenerationForSpecies(id)
  if (generation == null || !hasBwAnimated(id, slot)) return null
  const padded = String(id).padStart(3, '0')
  const parts = `${slot.side}-${slot.shiny ? 's' : 'n'}${slot.female ? '-f' : ''}`
  return `${RELEASE_BASE}/bw-gen${generation}/${padded}-bw-${parts}.webp`
}

export interface BwTile {
  slot: BwSlot
  url: string
  /** "Front", "Back". */
  sideLabel: string
  /** "Regular", "Shiny", and " · Female" where a female file exists. */
  variantLabel: string
  testId: string
}

/**
 * Every animated slot this species actually has, in reading order:
 * front before back, regular before shiny, male before female.
 */
export function bwAnimatedTiles(id: number): BwTile[] {
  const tiles: BwTile[] = []
  for (const side of ['front', 'back'] as const) {
    for (const shiny of [false, true]) {
      for (const female of [false, true]) {
        const slot: BwSlot = { side, shiny, female }
        const url = bwAnimatedUrl(id, slot)
        if (!url) continue
        tiles.push({
          slot,
          url,
          sideLabel: side === 'front' ? 'Front' : 'Back',
          variantLabel:
            (shiny ? 'Shiny' : 'Regular') + (female ? ' · Female' : hasFemale(id) ? ' · Male' : ''),
          testId: `sprite-bw-${side}-${shiny ? 's' : 'n'}${female ? '-f' : ''}`,
        })
      }
    }
  }
  return tiles
}

/** Whether any female file exists, i.e. whether the male tiles need labelling. */
function hasFemale(id: number): boolean {
  return (maskFor(id) & 0xf0) !== 0
}

/** Total animated slots across the whole in-scope range -- used by the audit. */
export function bwAnimatedCount(): number {
  let n = 0
  for (let id = BW_FIRST_ID; id <= BW_LAST_ID; id++) {
    let m = maskFor(id)
    while (m) {
      n += m & 1
      m >>= 1
    }
  }
  return n
}
