/**
 * Move flags the PokeAPI snapshot does not carry: sound, punch, powder, bite,
 * pulse, dance and ballistic.
 *
 * Generated by scripts/build-supplement.mjs from Bulbapedia categories.
 * Re-run that script to refresh; do not edit this file by hand.
 *
 * SEVEN FLAGS, NOT EIGHT -- contact is absent and that is a finding rather than
 * an oversight. Bulbapedia documents it neither as an inclusion list nor as an
 * exception list (every candidate category title returns DOES NOT EXIST, and
 * none of the 91 real "Moves that ..." categories concerns it), and the PokeAPI
 * snapshot this project builds from has no move-flag resource and no `flags`
 * field on a move. There is no source for it in the current data plan.
 *
 * NAMES ARE BUNDLE SLUGS, matched against moves.json rather than transcribed --
 * every name here resolved to a move the bundle carries in Gen 1-4 scope, and
 * the generator throws rather than emitting a short list if one stops matching.
 *
 * ERA: these are properties of the MOVE, not of a generation, so nothing here is
 * era-gated. A caller showing them still gates on whether the move existed yet,
 * the same way every other move field does.
 */

export const MOVE_FLAGS = [
  'sound',
  'punch',
  'powder',
  'bite',
  'pulse',
  'dance',
  'ballistic',
] as const

export type MoveFlag = (typeof MOVE_FLAGS)[number]

/** Move name slugs per flag, sorted, as of the snapshot above. */
export const MOVES_BY_FLAG: Record<MoveFlag, readonly string[]> = {
  sound: [
  'bug-buzz',
  'chatter',
  'grass-whistle',
  'growl',
  'heal-bell',
  'howl',
  'hyper-voice',
  'metal-sound',
  'perish-song',
  'roar',
  'screech',
  'shadow-panic',
  'sing',
  'snore',
  'supersonic',
  'uproar',
  ],
  punch: [
  'bullet-punch',
  'comet-punch',
  'dizzy-punch',
  'drain-punch',
  'dynamic-punch',
  'fire-punch',
  'focus-punch',
  'hammer-arm',
  'ice-punch',
  'mach-punch',
  'mega-punch',
  'meteor-mash',
  'shadow-punch',
  'sky-uppercut',
  'thunder-punch',
  ],
  powder: [
  'cotton-spore',
  'poison-powder',
  'sleep-powder',
  'spore',
  'stun-spore',
  ],
  bite: [
  'bite',
  'crunch',
  'fire-fang',
  'hyper-fang',
  'ice-fang',
  'poison-fang',
  'thunder-fang',
  ],
  pulse: [
  'aura-sphere',
  'dark-pulse',
  'dragon-pulse',
  'water-pulse',
  ],
  dance: [
  'dragon-dance',
  'feather-dance',
  'lunar-dance',
  'petal-dance',
  'swords-dance',
  'teeter-dance',
  ],
  ballistic: [
  'aura-sphere',
  'barrage',
  'bullet-seed',
  'egg-bomb',
  'energy-ball',
  'focus-blast',
  'gyro-ball',
  'ice-ball',
  'magnet-bomb',
  'mist-ball',
  'mud-bomb',
  'octazooka',
  'rock-blast',
  'rock-wrecker',
  'seed-bomb',
  'shadow-ball',
  'sludge-bomb',
  'weather-ball',
  'zap-cannon',
  ],
}

/*
  Inverted once at module load rather than scanned per call: the Movedex asks
  this per row, and seven linear searches per move is work that only has to
  happen once. A Map of name -> flags, built from the tables above so the two
  cannot drift.
*/
const FLAGS_BY_MOVE = new Map<string, MoveFlag[]>()
for (const flag of MOVE_FLAGS) {
  for (const name of MOVES_BY_FLAG[flag]) {
    const existing = FLAGS_BY_MOVE.get(name)
    if (existing) existing.push(flag)
    else FLAGS_BY_MOVE.set(name, [flag])
  }
}

/** Flags carried by a move, in MOVE_FLAGS order. Empty for most moves. */
export function moveFlags(moveName: string): readonly MoveFlag[] {
  return FLAGS_BY_MOVE.get(moveName) ?? []
}

/** Whether a move carries one particular flag. */
export function moveHasFlag(moveName: string, flag: MoveFlag): boolean {
  return MOVES_BY_FLAG[flag].includes(moveName)
}

/** Total distinct moves carrying at least one flag. */
export const FLAGGED_MOVE_COUNT = FLAGS_BY_MOVE.size
